// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebProje.Context;

namespace WebProje.Migrations
{
    [DbContext(typeof(BarinakDbContext))]
    [Migration("20210101194524_Create_Database")]
    partial class Create_Database
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("WebProje.Entity.AsiTakvimi", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("asi_adi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("asi_durumu")
                        .HasColumnType("bit");

                    b.Property<DateTime>("asi_tarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("AsiTakvimi");
                });

            modelBuilder.Entity("WebProje.Entity.BarinakBilgileri", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("adres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("barinak_adi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("barinak_hakkinda")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("eposta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("il")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ilce")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mahalle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefon_numarasi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("BarinakBilgileri");
                });

            modelBuilder.Entity("WebProje.Entity.BeslenmeProgrami", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("aksam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("beslenme_programi_adi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gece")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ogle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sabah")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("BeslenmeProgrami");
                });

            modelBuilder.Entity("WebProje.Entity.CalismaSaatleri", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("acilis_saati")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("barinakid")
                        .HasColumnType("int");

                    b.Property<bool>("durum")
                        .HasColumnType("bit");

                    b.Property<string>("gun")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("kapanis_saati")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("barinakid");

                    b.ToTable("CalismaSaatleri");
                });

            modelBuilder.Entity("WebProje.Entity.Cinsiyet", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("cinsiyet")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Cinsiyet");
                });

            modelBuilder.Entity("WebProje.Entity.HayvanCinsleri", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("cinsin_genel_ozellikleri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hayvan_cinsi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("hayvan_turuid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("hayvan_turuid");

                    b.ToTable("HayvanCinsleri");
                });

            modelBuilder.Entity("WebProje.Entity.HayvanFotograflari", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("fotograf_adi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("hayvanid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("hayvanid");

                    b.ToTable("HayvanFotograflari");
                });

            modelBuilder.Entity("WebProje.Entity.HayvanTurleri", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("hayvan_turu")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("HayvanTurleri");
                });

            modelBuilder.Entity("WebProje.Entity.KayitliHayvanlar", b =>
                {
                    b.Property<int>("id")
                        .HasColumnType("int");

                    b.Property<string>("adi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("beslenme_programiid")
                        .HasColumnType("int");

                    b.Property<int?>("cinsiid")
                        .HasColumnType("int");

                    b.Property<int?>("cinsiyetiid")
                        .HasColumnType("int");

                    b.Property<string>("hakkinda")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("saglik_durumuid")
                        .HasColumnType("int");

                    b.Property<int?>("sahiplenebilirlik_durumuid")
                        .HasColumnType("int");

                    b.Property<int>("yas")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("beslenme_programiid");

                    b.HasIndex("cinsiid");

                    b.HasIndex("cinsiyetiid");

                    b.HasIndex("saglik_durumuid");

                    b.HasIndex("sahiplenebilirlik_durumuid");

                    b.ToTable("KayitliHayvanlar");
                });

            modelBuilder.Entity("WebProje.Entity.KullaniciRolu", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("rol")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("KullaniciRolu");
                });

            modelBuilder.Entity("WebProje.Entity.Kullanicilar", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("adres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("eposta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("il")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ilce")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("kullanici_roluid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("mahalle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sifre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("soyad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("kullanici_roluid");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("WebProje.Entity.SaglikDurumu", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("durum")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.ToTable("SaglikDurumu");
                });

            modelBuilder.Entity("WebProje.Entity.SahiplenebilirlikDurumu", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("durum")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.ToTable("SahiplenebilirlikDurumu");
                });

            modelBuilder.Entity("WebProje.Entity.SahiplenmeBasvuruDurumlari", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("durum")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("SahiplenmeBasvuruDurumlari");
                });

            modelBuilder.Entity("WebProje.Entity.SahiplenmeTalepleri", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("basvuran_kullaniciid")
                        .HasColumnType("int");

                    b.Property<int?>("basvuru_durumuid")
                        .HasColumnType("int");

                    b.Property<int?>("basvurulan_hayvanid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("basvuran_kullaniciid");

                    b.HasIndex("basvuru_durumuid");

                    b.HasIndex("basvurulan_hayvanid");

                    b.ToTable("SahiplenmeTalepleri");
                });

            modelBuilder.Entity("WebProje.Entity.CalismaSaatleri", b =>
                {
                    b.HasOne("WebProje.Entity.BarinakBilgileri", "barinak")
                        .WithMany("calisma_saatleri")
                        .HasForeignKey("barinakid");

                    b.Navigation("barinak");
                });

            modelBuilder.Entity("WebProje.Entity.HayvanCinsleri", b =>
                {
                    b.HasOne("WebProje.Entity.HayvanTurleri", "hayvan_turu")
                        .WithMany("hayvan_cinsleri")
                        .HasForeignKey("hayvan_turuid");

                    b.Navigation("hayvan_turu");
                });

            modelBuilder.Entity("WebProje.Entity.HayvanFotograflari", b =>
                {
                    b.HasOne("WebProje.Entity.KayitliHayvanlar", "hayvan")
                        .WithMany("fotograflari")
                        .HasForeignKey("hayvanid");

                    b.Navigation("hayvan");
                });

            modelBuilder.Entity("WebProje.Entity.KayitliHayvanlar", b =>
                {
                    b.HasOne("WebProje.Entity.BeslenmeProgrami", "beslenme_programi")
                        .WithMany("hayvanklar")
                        .HasForeignKey("beslenme_programiid");

                    b.HasOne("WebProje.Entity.HayvanCinsleri", "cinsi")
                        .WithMany("kayitli_hayvanlar")
                        .HasForeignKey("cinsiid");

                    b.HasOne("WebProje.Entity.Cinsiyet", "cinsiyeti")
                        .WithMany("hayvanlar")
                        .HasForeignKey("cinsiyetiid");

                    b.HasOne("WebProje.Entity.AsiTakvimi", "asi_takvimi")
                        .WithOne("hayvan")
                        .HasForeignKey("WebProje.Entity.KayitliHayvanlar", "id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebProje.Entity.SaglikDurumu", "saglik_durumu")
                        .WithMany("hayvanlar")
                        .HasForeignKey("saglik_durumuid");

                    b.HasOne("WebProje.Entity.SahiplenebilirlikDurumu", "sahiplenebilirlik_durumu")
                        .WithMany("hayvanlar")
                        .HasForeignKey("sahiplenebilirlik_durumuid");

                    b.Navigation("asi_takvimi");

                    b.Navigation("beslenme_programi");

                    b.Navigation("cinsi");

                    b.Navigation("cinsiyeti");

                    b.Navigation("saglik_durumu");

                    b.Navigation("sahiplenebilirlik_durumu");
                });

            modelBuilder.Entity("WebProje.Entity.Kullanicilar", b =>
                {
                    b.HasOne("WebProje.Entity.KullaniciRolu", "kullanici_rolu")
                        .WithMany("kullanicilar")
                        .HasForeignKey("kullanici_roluid");

                    b.Navigation("kullanici_rolu");
                });

            modelBuilder.Entity("WebProje.Entity.SahiplenmeTalepleri", b =>
                {
                    b.HasOne("WebProje.Entity.Kullanicilar", "basvuran_kullanici")
                        .WithMany("basvuru_talepleri")
                        .HasForeignKey("basvuran_kullaniciid");

                    b.HasOne("WebProje.Entity.SahiplenmeBasvuruDurumlari", "basvuru_durumu")
                        .WithMany("talepler")
                        .HasForeignKey("basvuru_durumuid");

                    b.HasOne("WebProje.Entity.KayitliHayvanlar", "basvurulan_hayvan")
                        .WithMany("sahiplenme_basvurulari")
                        .HasForeignKey("basvurulan_hayvanid");

                    b.Navigation("basvuran_kullanici");

                    b.Navigation("basvuru_durumu");

                    b.Navigation("basvurulan_hayvan");
                });

            modelBuilder.Entity("WebProje.Entity.AsiTakvimi", b =>
                {
                    b.Navigation("hayvan");
                });

            modelBuilder.Entity("WebProje.Entity.BarinakBilgileri", b =>
                {
                    b.Navigation("calisma_saatleri");
                });

            modelBuilder.Entity("WebProje.Entity.BeslenmeProgrami", b =>
                {
                    b.Navigation("hayvanklar");
                });

            modelBuilder.Entity("WebProje.Entity.Cinsiyet", b =>
                {
                    b.Navigation("hayvanlar");
                });

            modelBuilder.Entity("WebProje.Entity.HayvanCinsleri", b =>
                {
                    b.Navigation("kayitli_hayvanlar");
                });

            modelBuilder.Entity("WebProje.Entity.HayvanTurleri", b =>
                {
                    b.Navigation("hayvan_cinsleri");
                });

            modelBuilder.Entity("WebProje.Entity.KayitliHayvanlar", b =>
                {
                    b.Navigation("fotograflari");

                    b.Navigation("sahiplenme_basvurulari");
                });

            modelBuilder.Entity("WebProje.Entity.KullaniciRolu", b =>
                {
                    b.Navigation("kullanicilar");
                });

            modelBuilder.Entity("WebProje.Entity.Kullanicilar", b =>
                {
                    b.Navigation("basvuru_talepleri");
                });

            modelBuilder.Entity("WebProje.Entity.SaglikDurumu", b =>
                {
                    b.Navigation("hayvanlar");
                });

            modelBuilder.Entity("WebProje.Entity.SahiplenebilirlikDurumu", b =>
                {
                    b.Navigation("hayvanlar");
                });

            modelBuilder.Entity("WebProje.Entity.SahiplenmeBasvuruDurumlari", b =>
                {
                    b.Navigation("talepler");
                });
#pragma warning restore 612, 618
        }
    }
}
